const WORDS = [
  { hanzi: '好', pinyin: 'hǎo', en: 'good', tr: 'iyi', hsk: 1, compounds: ['你好', '很好', '好吃', '好看'] },
  { hanzi: '你', pinyin: 'nǐ', en: 'you', tr: 'sen', hsk: 1, compounds: ['你好', '你们'] },
  { hanzi: '我', pinyin: 'wǒ', en: 'I / me', tr: 'ben', hsk: 1, compounds: ['我们', '我的'] },
  { hanzi: '叫', pinyin: 'jiào', en: 'to call', tr: 'adlandırmak / çağırmak', hsk: 1, compounds: ['叫门'] },
  { hanzi: '是', pinyin: 'shì', en: 'to be', tr: 'olmak (-dır)', hsk: 1, compounds: ['是不是', '但是'] },
  { hanzi: '人', pinyin: 'rén', en: 'person', tr: 'insan / kişi', hsk: 1, compounds: ['中国人', '外国人', '男人', '女人'] },
  { hanzi: '中国', pinyin: 'Zhōngguó', en: 'China', tr: 'Çin', hsk: 1, compounds: ['中', '国'] },
  { hanzi: '中', pinyin: 'zhōng', en: 'middle', tr: 'orta', hsk: 1, compounds: ['中国', '中午', '中间', '中文'] },
  { hanzi: '国', pinyin: 'guó', en: 'country', tr: 'ülke', hsk: 1, compounds: ['中国', '外国', '国家'] },
  { hanzi: '老师', pinyin: 'lǎoshī', en: 'teacher', tr: 'öğretmen', hsk: 1, compounds: ['老', '师'] },
  { hanzi: '学生', pinyin: 'xuésheng', en: 'student', tr: 'öğrenci', hsk: 1, compounds: ['学', '生'] },
  { hanzi: '学', pinyin: 'xué', en: 'study', tr: 'öğrenmek', hsk: 1, compounds: ['学生', '学习', '学校', '大学'] },
  { hanzi: '生', pinyin: 'shēng', en: 'born / life', tr: 'doğmak / hayat', hsk: 1, compounds: ['学生', '生日', '医生', '生活', '女生', '男生'] },
  { hanzi: '这', pinyin: 'zhè', en: 'this', tr: 'bu', hsk: 1, compounds: ['这个', '这里'] },
  { hanzi: '的', pinyin: 'de', en: 'possessive particle', tr: 'iyelik eki (-ın)', hsk: 1, compounds: ['我的', '你的', '好的'] },
  { hanzi: '书', pinyin: 'shū', en: 'book', tr: 'kitap', hsk: 1, compounds: ['书店', '书架', '看书', '图书馆'] },
  { hanzi: '有', pinyin: 'yǒu', en: 'to have', tr: 'sahip olmak / var', hsk: 1, compounds: ['没有', '有名'] },
  { hanzi: '没', pinyin: 'méi', en: 'not', tr: 'yok', hsk: 1, compounds: ['没有', '没关系'] },
  { hanzi: '没有', pinyin: 'méiyǒu', en: 'not have', tr: 'sahip olmamak', hsk: 1, compounds: ['没', '有'] },
  { hanzi: '本', pinyin: 'běn', en: 'measure word for books', tr: 'kitap için miktar kelimesi', hsk: 1, compounds: ['日本', '本子', '书本'] },
  { hanzi: '什么', pinyin: 'shénme', en: 'what', tr: 'ne', hsk: 1, compounds: ['什么时候', '为什么'] },
  { hanzi: '家', pinyin: 'jiā', en: 'home / family', tr: 'ev / aile', hsk: 1, compounds: ['全家', '大家', '回家'] },
  { hanzi: '谁', pinyin: 'shéi', en: 'who', tr: 'kim', hsk: 1, compounds: [] },
  { hanzi: '爸爸', pinyin: 'bàba', en: 'dad', tr: 'baba', hsk: 1, compounds: ['爸'] },
  { hanzi: '妈妈', pinyin: 'māma', en: 'mom', tr: 'anne', hsk: 1, compounds: ['妈'] },
  { hanzi: '哥哥', pinyin: 'gēge', en: 'older brother', tr: 'abi', hsk: 1, compounds: ['哥'] },
  { hanzi: '弟弟', pinyin: 'dìdi', en: 'younger brother', tr: 'erkek kardeş', hsk: 1, compounds: ['弟'] },
  { hanzi: '姐姐', pinyin: 'jiějie', en: 'older sister', tr: 'abla', hsk: 1, compounds: ['姐'] },
  { hanzi: '妹妹', pinyin: 'mèimei', en: 'younger sister', tr: 'kız kardeş', hsk: 1, compounds: ['妹'] },
  { hanzi: '工作', pinyin: 'gōngzuò', en: 'work', tr: 'çalışmak / iş', hsk: 1, compounds: ['工人'] },
  { hanzi: '学习', pinyin: 'xuéxí', en: 'to study', tr: 'çalışmak', hsk: 1, compounds: ['学', '习'] },
  { hanzi: '汉语', pinyin: 'Hànyǔ', en: 'Chinese language', tr: 'Çince', hsk: 1, compounds: ['汉', '语'] },
  { hanzi: '语', pinyin: 'yǔ', en: 'language', tr: 'dil', hsk: 1, compounds: ['汉语', '英语', '语言'] },
  { hanzi: '朋友', pinyin: 'péngyou', en: 'friend', tr: 'arkadaş', hsk: 1, compounds: ['好朋友'] },
  { hanzi: '名字', pinyin: 'míngzi', en: 'name', tr: 'isim', hsk: 1, compounds: ['名', '字'] },
  { hanzi: '哪', pinyin: 'nǎ', en: 'which', tr: 'hangi', hsk: 1, compounds: ['哪儿', '哪个'] },
  { hanzi: '外国', pinyin: 'wàiguó', en: 'foreign country', tr: 'yabancı ülke', hsk: 1, compounds: ['外', '国'] },
  { hanzi: '外', pinyin: 'wài', en: 'outside', tr: 'dış', hsk: 1, compounds: ['外边', '外国', '外面'] },
  { hanzi: '都', pinyin: 'dōu', en: 'all', tr: 'hepsi', hsk: 1, compounds: ['都是'] },
  { hanzi: '请', pinyin: 'qǐng', en: 'please', tr: 'lütfen', hsk: 1, compounds: ['请问', '请进', '请客'] },
  { hanzi: '天', pinyin: 'tiān', en: 'day / sky', tr: 'gün', hsk: 1, compounds: ['今天', '明天', '昨天', '星期天', '天气'] },
  { hanzi: '今天', pinyin: 'jīntiān', en: 'today', tr: 'bugün', hsk: 1, compounds: ['今', '天'] },
  { hanzi: '明天', pinyin: 'míngtiān', en: 'tomorrow', tr: 'yarın', hsk: 1, compounds: ['明', '天'] },
  { hanzi: '昨天', pinyin: 'zuótiān', en: 'yesterday', tr: 'dün', hsk: 1, compounds: ['昨', '天'] },
  { hanzi: '生日', pinyin: 'shēngrì', en: 'birthday', tr: 'doğum günü', hsk: 1, compounds: ['生', '日'] },
  { hanzi: '日', pinyin: 'rì', en: 'day / sun', tr: 'gün / güneş', hsk: 1, compounds: ['生日', '日本', '日记'] },
  { hanzi: '快乐', pinyin: 'kuàilè', en: 'happy', tr: 'mutlu', hsk: 1, compounds: ['快', '乐'] },
  { hanzi: '谢谢', pinyin: 'xièxie', en: 'thanks', tr: 'teşekkürler', hsk: 1, compounds: ['不用谢'] },
  { hanzi: '月', pinyin: 'yuè', en: 'month', tr: 'ay', hsk: 1, compounds: ['一月', '二月', '几个月'] },
  { hanzi: '星期', pinyin: 'xīngqī', en: 'week', tr: 'hafta', hsk: 1, compounds: ['星', '期', '星期天'] },
  { hanzi: '很', pinyin: 'hěn', en: 'very', tr: 'çok', hsk: 1, compounds: ['很好', '很高兴', '很大'] },
  { hanzi: '现在', pinyin: 'xiànzài', en: 'now', tr: 'şimdi', hsk: 1, compounds: ['现', '在'] },
  { hanzi: '点', pinyin: 'diǎn', en: 'o\'clock', tr: 'saat (vakit)', hsk: 1, compounds: ['几点', '一点儿'] },
  { hanzi: '分', pinyin: 'fēn', en: 'minute', tr: 'dakika', hsk: 1, compounds: ['分钟'] },
  { hanzi: '早上', pinyin: 'zǎoshang', en: 'morning', tr: 'sabah', hsk: 1, compounds: ['早', '上'] },
  { hanzi: '晚上', pinyin: 'wǎnshang', en: 'evening', tr: 'akşam', hsk: 1, compounds: ['晚', '上'] },
  { hanzi: '上午', pinyin: 'shàngwǔ', en: 'morning', tr: 'öğleden önce', hsk: 1, compounds: ['上', '午'] },
  { hanzi: '下午', pinyin: 'xiàwǔ', en: 'afternoon', tr: 'öğleden sonra', hsk: 1, compounds: ['下', '午'] },
  { hanzi: '中午', pinyin: 'zhōngwǔ', en: 'noon', tr: 'öğle', hsk: 1, compounds: ['中', '午'] },
  { hanzi: '上', pinyin: 'shàng', en: 'up / above', tr: 'yukarı', hsk: 1, compounds: ['上午', '上边', '上课', '上班'] },
  { hanzi: '下', pinyin: 'xià', en: 'down / below', tr: 'aşağı', hsk: 1, compounds: ['下午', '下边', '下课', '下雨'] },
  { hanzi: '午', pinyin: 'wǔ', en: 'noon', tr: 'öğle', hsk: 1, compounds: ['上午', '中午', '下午'] },
  { hanzi: '课', pinyin: 'kè', en: 'class / lesson', tr: 'ders', hsk: 1, compounds: ['上课', '下课'] },
  { hanzi: '半', pinyin: 'bàn', en: 'half', tr: 'buçuk / yarım', hsk: 1, compounds: ['一半', '半个'] },
  { hanzi: '睡觉', pinyin: 'shuìjiào', en: 'sleep', tr: 'uyumak', hsk: 1, compounds: ['睡', '觉'] },
  { hanzi: '银行', pinyin: 'yínháng', en: 'bank', tr: 'banka', hsk: 2, compounds: ['银', '行'] },
  { hanzi: '在', pinyin: 'zài', en: 'at / in', tr: 'bulunmak', hsk: 1, compounds: ['现在', '在家'] },
  { hanzi: '哪儿', pinyin: 'nǎr', en: 'where', tr: 'nerede', hsk: 1, compounds: ['哪'] },
  { hanzi: '边', pinyin: 'bian', en: 'side', tr: 'kenar / taraf', hsk: 1, compounds: ['东边', '西边', '南边', '北边', '前边', '后边', '上边', '下边', '旁边'] },
  { hanzi: '东', pinyin: 'dōng', en: 'east', tr: 'doğu', hsk: 1, compounds: ['东边', '东西'] },
  { hanzi: '西', pinyin: 'xī', en: 'west', tr: 'batı', hsk: 1, compounds: ['西边', '东西'] },
  { hanzi: '南', pinyin: 'nán', en: 'south', tr: 'güney', hsk: 1, compounds: ['南边'] },
  { hanzi: '北', pinyin: 'běi', en: 'north', tr: 'kuzey', hsk: 1, compounds: ['北边', '北京'] },
  { hanzi: '前', pinyin: 'qián', en: 'front', tr: 'ön', hsk: 1, compounds: ['前边', '以前'] },
  { hanzi: '后', pinyin: 'hòu', en: 'back', tr: 'arka', hsk: 1, compounds: ['后边', '以后'] },
  { hanzi: '地方', pinyin: 'dìfang', en: 'place', tr: 'yer', hsk: 1, compounds: ['地', '方'] },
  { hanzi: '学校', pinyin: 'xuéxiào', en: 'school', tr: 'okul', hsk: 1, compounds: ['学', '校'] },
  { hanzi: '房间', pinyin: 'fángjiān', en: 'room', tr: 'oda', hsk: 2, compounds: ['房', '间'] },
  { hanzi: '间', pinyin: 'jiān', en: 'room / between', tr: 'oda / arası', hsk: 1, compounds: ['房间', '中间', '时间'] },
  { hanzi: '里', pinyin: 'lǐ', en: 'inside', tr: 'içinde', hsk: 1, compounds: ['里边', '家里'] },
  { hanzi: '桌子', pinyin: 'zhuōzi', en: 'desk / table', tr: 'masa', hsk: 1, compounds: ['桌'] },
  { hanzi: '旁边', pinyin: 'pángbiān', en: 'beside', tr: 'yan taraf', hsk: 1, compounds: ['旁', '边'] },
  { hanzi: '中间', pinyin: 'zhōngjiān', en: 'middle', tr: 'orta', hsk: 1, compounds: ['中', '间'] },
  { hanzi: '或者', pinyin: 'huòzhě', en: 'or', tr: 'veya / ya da', hsk: 2, compounds: ['或', '者'] },
  { hanzi: '图书馆', pinyin: 'túshūguǎn', en: 'library', tr: 'kütüphane', hsk: 2, compounds: ['图', '书', '馆'] },
  { hanzi: '写', pinyin: 'xiě', en: 'to write', tr: 'yazmak', hsk: 1, compounds: ['写信', '写字'] },
  { hanzi: '信', pinyin: 'xìn', en: 'letter', tr: 'mektup', hsk: 1, compounds: ['写信'] },
  { hanzi: '同屋', pinyin: 'tóngwū', en: 'roommate', tr: 'oda arkadaşı', hsk: 2, compounds: ['同', '屋', '同学'] },
  { hanzi: '常常', pinyin: 'chángcháng', en: 'often', tr: 'sık sık', hsk: 2, compounds: ['常'] },
  { hanzi: '电视', pinyin: 'diànshì', en: 'television', tr: 'televizyon', hsk: 1, compounds: ['电', '视', '看电视'] },
  { hanzi: '聊天儿', pinyin: 'liáotiānr', en: 'to chat', tr: 'sohbet etmek', hsk: 2, compounds: ['聊', '天'] },
  { hanzi: '食堂', pinyin: 'shítáng', en: 'dining hall', tr: 'yemekhane', hsk: 2, compounds: ['食', '堂'] },
  { hanzi: '去', pinyin: 'qù', en: 'to go', tr: 'gitmek', hsk: 1, compounds: ['去年', '进去'] },
  { hanzi: '来', pinyin: 'lái', en: 'to come', tr: 'gelmek', hsk: 1, compounds: ['回来', '出来'] },
  { hanzi: '买', pinyin: 'mǎi', en: 'to buy', tr: 'satın almak', hsk: 1, compounds: ['买东西'] },
  { hanzi: '卖', pinyin: 'mài', en: 'to sell', tr: 'satmak', hsk: 1, compounds: ['买卖'] },
  { hanzi: '东西', pinyin: 'dōngxi', en: 'thing', tr: 'eşya / şey', hsk: 1, compounds: ['东', '西', '买东西'] },
  { hanzi: '苹果', pinyin: 'píngguǒ', en: 'apple', tr: 'elma', hsk: 1, compounds: ['果', '水果'] },
  { hanzi: '钱', pinyin: 'qián', en: 'money', tr: 'para', hsk: 1, compounds: ['多少钱', '有钱'] },
  { hanzi: '贵', pinyin: 'guì', en: 'expensive', tr: 'pahalı', hsk: 2, compounds: ['太贵了'] },
  { hanzi: '便宜', pinyin: 'piányi', en: 'cheap', tr: 'ucuz', hsk: 2, compounds: ['便', '宜'] },
  { hanzi: '吃', pinyin: 'chī', en: 'to eat', tr: 'yemek', hsk: 1, compounds: ['吃饭', '好吃'] },
  { hanzi: '饭', pinyin: 'fàn', en: 'meal / rice', tr: 'yemek / pilav', hsk: 1, compounds: ['吃饭', '米饭', '早饭'] },
  { hanzi: '喝', pinyin: 'hē', en: 'to drink', tr: 'içmek', hsk: 1, compounds: ['喝水', '喝茶'] },
  { hanzi: '水', pinyin: 'shuǐ', en: 'water', tr: 'su', hsk: 1, compounds: ['喝水', '水果'] },
  { hanzi: '茶', pinyin: 'chá', en: 'tea', tr: 'çay', hsk: 1, compounds: ['喝茶'] },
  { hanzi: '喜欢', pinyin: 'xǐhuan', en: 'to like', tr: 'hoşlanmak', hsk: 1, compounds: ['喜', '欢'] },
  { hanzi: '看', pinyin: 'kàn', en: 'to look / watch', tr: 'bakmak / izlemek', hsk: 1, compounds: ['看见', '看书', '看电视'] },
  { hanzi: '听', pinyin: 'tīng', en: 'to listen', tr: 'dinlemek', hsk: 1, compounds: ['听音乐', '听说'] },
  { hanzi: '音乐', pinyin: 'yīnyuè', en: 'music', tr: 'müzik', hsk: 2, compounds: ['音', '乐', '听音乐'] },
  { hanzi: '大', pinyin: 'dà', en: 'big', tr: 'büyük', hsk: 1, compounds: ['大学', '大家'] },
  { hanzi: '小', pinyin: 'xiǎo', en: 'small', tr: 'küçük', hsk: 1, compounds: ['小学', '小时'] },
  { hanzi: '多', pinyin: 'duō', en: 'many', tr: 'çok', hsk: 1, compounds: ['多少', '很多'] },
  { hanzi: '少', pinyin: 'shǎo', en: 'few', tr: 'az', hsk: 1, compounds: ['多少', '很少'] },
  { hanzi: '天气', pinyin: 'tiānqì', en: 'weather', tr: 'hava durumu', hsk: 1, compounds: ['天', '气'] },
  { hanzi: '冷', pinyin: 'lěng', en: 'cold', tr: 'soğuk', hsk: 1, compounds: ['很冷'] },
  { hanzi: '热', pinyin: 'rè', en: 'hot', tr: 'sıcak', hsk: 1, compounds: ['很热'] },
  { hanzi: '下雨', pinyin: 'xià yǔ', en: 'to rain', tr: 'yağmur yağması', hsk: 1, compounds: ['下', '雨'] },
  { hanzi: '做', pinyin: 'zuò', en: 'to do', tr: 'yapmak', hsk: 1, compounds: ['做饭', '做事'] },
  { hanzi: '运动', pinyin: 'yùndòng', en: 'sports / exercise', tr: 'spor / egzersiz', hsk: 2, compounds: ['运', '动'] },
  { hanzi: '想', pinyin: 'xiǎng', en: 'to think / want', tr: 'düşünmek / istemek', hsk: 1, compounds: ['想法'] },
  { hanzi: '要', pinyin: 'yào', en: 'to want / will', tr: 'istemek / -ecek', hsk: 1, compounds: ['不要'] },
  { hanzi: '会', pinyin: 'huì', en: 'can / know how', tr: 'yapabilmek / bilecek', hsk: 1, compounds: ['不会', '开会'] },
  { hanzi: '能', pinyin: 'néng', en: 'can / be able to', tr: 'yapabilmek', hsk: 1, compounds: ['不能'] },
  { hanzi: '认识', pinyin: 'rènshi', en: 'to know (somebody)', tr: 'tanımak', hsk: 1, compounds: ['认', '识'] },
  { hanzi: '觉得', pinyin: 'juéde', en: 'to feel / think', tr: 'hissetmek / düşünmek', hsk: 2, compounds: ['觉', '得'] },
  { hanzi: '块', pinyin: 'kuài', en: 'piece / yuan', tr: 'parça / Yuan (para)', hsk: 1, compounds: ['一块儿'] },
  { hanzi: '漂亮', pinyin: 'piàoliang', en: 'pretty / beautiful', tr: 'güzel', hsk: 1, compounds: ['漂', '亮'] },
  { hanzi: '太', pinyin: 'tài', en: 'too', tr: 'aşırı', hsk: 1, compounds: ['太好了', '太太'] },
  { hanzi: '了', pinyin: 'le', en: 'completed action marker', tr: 'geçmiş zaman eki', hsk: 1, compounds: ['太好了', '吃饭了'] },
  { hanzi: '吗', pinyin: 'ma', en: 'question particle', tr: 'soru eki (mı/mi)', hsk: 1, compounds: ['好吗', '是吗'] },
  { hanzi: '呢', pinyin: 'ne', en: 'question particle', tr: 'soru eki (ya ...?)', hsk: 1, compounds: ['你呢'] }
];

const SENTENCES = [
  { cn: '你好，我叫大卫。', py: 'Nǐ hǎo, wǒ jiào Dàwèi.', tr: 'Merhaba, benim adım David.', blocks: ['你', '好', '，', '我', '叫', '大卫', '。'] },
  { cn: '你是哪国人？', py: 'Nǐ shì nǎ guó rén?', tr: 'Sen hangi ülkedensin?', blocks: ['你', '是', '哪', '国', '人', '？'] },
  { cn: '我们是学生。', py: 'Wǒmen shì xuésheng.', tr: 'Biz öğrenciyiz.', blocks: ['我们', '是', '学生', '。'] },
  { cn: '这是我的书。', py: 'Zhè shì wǒ de shū.', tr: 'Bu benim kitabım.', blocks: ['这', '是', '我', '的', '书', '。'] },
  { cn: '你家有几口人？', py: 'Nǐ jiā yǒu jǐ kǒu rén?', tr: 'Ailende kaç kişi var?', blocks: ['你', '家', '有', '几', '口', '人', '？'] },
  { cn: '明天星期几？', py: 'Míngtiān xīngqī jǐ?', tr: 'Yarın günlerden ne?', blocks: ['明天', '星期', '几', '？'] },
  { cn: '祝你生日快乐！', py: 'Zhù nǐ shēngrì kuàilè!', tr: 'Doğum günün kutlu olsun!', blocks: ['祝', '你', '生日', '快乐', '！'] },
  { cn: '现在几点？', py: 'Xiànzài jǐ diǎn?', tr: 'Şu an saat kaç?', blocks: ['现在', '几', '点', '？'] },
  { cn: '银行在哪儿？', py: 'Yínháng zài nǎr?', tr: 'Banka nerede?', blocks: ['银行', '在', '哪儿', '？'] },
  { cn: '桌子上有一本书。', py: 'Zhuōzi shang yǒu yì běn shū.', tr: 'Masanın üzerinde bir kitap var.', blocks: ['桌子', '上', '有', '一', '本', '书', '。'] },
  { cn: '我不去学校。', py: 'Wǒ bú qù xuéxiào.', tr: 'Ben okula gitmiyorum.', blocks: ['我', '不', '去', '学校', '。'] },
  { cn: '他在房间里睡觉。', py: 'Tā zài fángjiān lǐ shuìjiào.', tr: 'O, odanın içinde uyuyor.', blocks: ['他', '在', '房间', '里', '睡觉', '。'] },
  { cn: '你去图书馆吗？', py: 'Nǐ qù túshūguǎn ma?', tr: 'Kütüphaneye gidiyor musun?', blocks: ['你', '去', '图书馆', '吗', '？'] },
  { cn: '我喜欢看电影。', py: 'Wǒ xǐhuan kàn diànyǐng.', tr: 'Film izlemeyi severim.', blocks: ['我', '喜欢', '看', '电影', '。'] },
  { cn: '这个苹果多少钱？', py: 'Zhège píngguǒ duōshao qián?', tr: 'Bu elma ne kadar?', blocks: ['这个', '苹果', '多少钱', '？'] },
  { cn: '太贵了，便宜一点儿吧。', py: 'Tài guì le, piányi yìdiǎnr ba.', tr: 'Çok pahalı, biraz ucuz olsun.', blocks: ['太贵了', '，', '便宜', '一点儿', '吧', '。'] },
  { cn: '你想喝点儿什么？', py: 'Nǐ xiǎng hē diǎnr shénme?', tr: 'Ne içmek istersin?', blocks: ['你', '想', '喝', '点儿', '什么', '？'] },
  { cn: '今天天气很热。', py: 'Jīntiān tiānqì hěn rè.', tr: 'Bugün hava很热。', blocks: ['今天', '天气', '很热', '。'] },
  { cn: '很高兴认识你。', py: 'Hěn gāoxìng rènshi nǐ.', tr: 'Seni tanıdığıma çok sevindim.', blocks: ['很高兴', '认识', '你', '。'] },
  { cn: '你在做什么呢？', py: 'Nǐ zài zuò shénme ne?', tr: 'Ne yapıyorsun?', blocks: ['你', '在', '做', '什么', '呢', '？'] }
];

module.exports = { WORDS, SENTENCES };
