const READING_DICT = {
  "我": { p: "wǒ", t: "ben" },
  "我们": { p: "wǒmen", t: "biz" },
  "叫": { p: "jiào", t: "adlandırılmak, -im adı ..." },
  "是": { p: "shì", t: "olmak (fiil)" },
  "法国": { p: "Fǎguó", t: "Fransa" },
  "人": { p: "rén", t: "kişi, insan" },
  "北京": { p: "Běijīng", t: "Pekin" },
  "语言": { p: "yǔyán", t: "dil (lisan)" },
  "大学": { p: "dàxué", t: "üniversite" },
  "留学生": { p: "liúxuéshēng", t: "yabancı öğrenci" },
  "班": { p: "bān", t: "sınıf" },
  "有": { p: "yǒu", t: "sahip olmak, var" },
  "学生": { p: "xuésheng", t: "öğrenci" },
  "个": { p: "gè", t: "genel sayı birimi" },
  "男生": { p: "nánshēng", t: "erkek öğrenci" },
  "女生": { p: "nǚshēng", t: "kız öğrenci" },
  "都": { p: "dōu", t: "hepsi, tüm" },
  "们": { p: "men", t: "çoğul eki" },
  "学习": { p: "xuéxí", t: "öğrenmek, çalışmak" },
  "汉语": { p: "Hànyǔ", t: "Çince (dil)" },
  "今天": { p: "jīntiān", t: "bugün" },
  "新同学": { p: "xīn tóngxué", t: "yeni sınıf arkadaşı" },
  "新": { p: "xīn", t: "yeni" },
  "同学": { p: "tóngxué", t: "sınıf arkadaşı" },
  "她": { p: "tā", t: "o (kadın)" },
  "他": { p: "tā", t: "o (erkek)" },
  "他们": { p: "tāmen", t: "onlar" },
  "韩国": { p: "Hánguó", t: "Kore" },
  "中国": { p: "Zhōngguó", t: "Çin" },
  "不是": { p: "bù shì", t: "değil" },
  "不": { p: "bù", t: "değil, -mez" },
  "词典": { p: "cídiǎn", t: "sözlük" },
  "本子": { p: "běnzi", t: "defter" },
  "笔": { p: "bǐ", t: "kalem" },
  "也": { p: "yě", t: "da, de (birliktelik)" },
  "没有": { p: "méiyǒu", t: "sahip değil, yok" },
  "自行车": { p: "zìxíngchē", t: "bisiklet" },
  "问": { p: "wèn", t: "sormak" },
  "又问": { p: "yòu wèn", t: "tekrar sormak" },
  "又": { p: "yòu", t: "tekrar, yine" },
  "家": { p: "jiā", t: "aile, ev" },
  "几口人": { p: "jǐ kǒu rén", t: "kaç aile üyesi" },
  "几": { p: "jǐ", t: "kaç? (10'dan küçük sayılar)" },
  "口": { p: "kǒu", t: "aile üyeleri için sayı birimi" },
  "爸爸": { p: "bàba", t: "baba" },
  "妈妈": { p: "māma", t: "anne" },
  "哥哥": { p: "gēge", t: "ağabey" },
  "和": { p: "hé", t: "ve" },
  "大夫": { p: "dàifu", t: "doktor" },
  "老师": { p: "lǎoshī", t: "öğretmen" },
  "做": { p: "zuò", t: "yapmak" },
  "什么": { p: "shénme", t: "ne" },
  "工作": { p: "gōngzuò", t: "iş, çalışmak" },
  "谁": { p: "shéi", t: "kim" },
  "这": { p: "zhè", t: "bu" },
  "那": { p: "nà", t: "şu, o" },
  "的": { p: "de", t: "aitlik eki (-ın, -in)" },
  "欢迎": { p: "huānyíng", t: "karşılamak, hoş geldin demek" },
  "丁": { p: "Dīng", t: "Ding (soyadı)" },
  "说": { p: "shuō", t: "söylemek, demek" },
  "你好": { p: "nǐ hǎo", t: "merhaba" },
  "你": { p: "nǐ", t: "sen" },
  "你们": { p: "nǐmen", t: "siz" },
  "好": { p: "hǎo", t: "iyi, güzel" },
  "很高兴": { p: "hěn gāoxìng", t: "çok mutlu" },
  "很": { p: "hěn", t: "çok" },
  "高兴": { p: "gāoxìng", t: "mutlu" },
  "谢谢": { p: "xièxie", t: "teşekkürler" },
  "认识": { p: "rènshi", t: "tanımak (birini)" },
  "大家": { p: "dàjiā", t: "herkes" },
  "英语": { p: "Yīngyǔ", t: "İngilizce" },
  "五月": { p: "wǔyuè", t: "Mayıs" },
  "九号": { p: "jiǔ hào", t: "9 (gün)" },
  "生日": { p: "shēngrì", t: "doğum günü" },
  "那天": { p: "nà tiān", t: "o gün" },
  "星期二": { p: "xīngqī'èr", t: "Salı" },
  "早上": { p: "zǎoshang", t: "sabah" },
  "几月": { p: "jǐ yuè", t: "hangi ay?" },
  "几号": { p: "jǐ hào", t: "ayın kaçı?" },
  "星期几": { p: "xīngqī jǐ", t: "haftanın hangi günü?" },
  "祝": { p: "zhù", t: "dilemek" },
  "快樂": { p: "kuàilè", t: "mutlu, sevinçli" },
  "中午": { p: "zhōngwǔ", t: "öğle vakti" },
  "一起": { p: "yīqǐ", t: "birlikte" },
  "去": { p: "qù", t: "gitmek" },
  "吃饭": { p: "chīfàn", t: "yemek yemek" },
  "吃": { p: "chī", t: "yemek (fiil)" },
  "米饭": { p: "mǐfàn", t: "pilav" },
  "还是": { p: "háishi", t: "yoksa (seçenek sorusu)" },
  "饺子": { p: "jiǎozi", t: "mantı (Çin mantısı)" },
  "喝": { p: "hē", t: "içmek" },
  "啤酒": { p: "píjiǔ", t: "bira" },
  "茶": { p: "chá", t: "çay" },
  "下午": { p: "xiàwǔ", t: "öğleden sonra" },
  "她们": { p: "tāmen", t: "onlar (kadın)" },
  "书店": { p: "shūdiàn", t: "kitapçı dükkanı" },
  "想买": { p: "xiǎng mǎi", t: "satın almak istemek" },
  "想": { p: "xiǎng", t: "istemek, düşünmek" },
  "买": { p: "mǎi", t: "satın almak" },
  "一本书": { p: "yī běn shū", t: "bir kitap" },
  "书": { p: "shū", t: "kitap" },
  "送给": { p: "sòng gěi", t: "hediye etmek, vermek" },
  "送": { p: "sòng", t: "hediye vermek" },
  "妹妹": { p: "mèimei", t: "küçük kız kardeş" },
  "售货员": { p: "shòuhuòyuán", t: "satış görevlisi" },
  "请问": { p: "qǐngwèn", t: "affedersiniz (soru sormak için)" },
  "多少钱": { p: "duōshao qián", t: "ne kadar (para)" },
  "二十五块": { p: "èrshíwǔ kuài", t: "25 yuan" },
  "二十块": { p: "èrshí kuài", t: "20 yuan" },
  "块": { p: "kuài", t: "yuan (Çin para birimi - konuşma)" },
  "元": { p: "yuán", t: "yuan (Çin para birimi - yazı)" },
  "太贵了": { p: "tài guì le", t: "çok pahalı!" },
  "太": { p: "tài", t: "çok, aşırı" },
  "了": { p: "le", t: "durum/değişim/tamamlanma eki" },
  "贵": { p: "guì", t: "pahalı" },
  "便宜": { p: "piányi", t: "ucuz" },
  "一点儿": { p: "yīdiǎnr", t: "biraz" },
  "吧": { p: "ba", t: "öneri eki (hadi/peki)" },
  "怎么样": { p: "zěnmeyàng", t: "nasıl? ne dersin?" },
  "行": { p: "xíng", t: "olur, tamam" },
  "我要了": { p: "wǒ yào le", t: "alıyorum, kabul ediyorum" },
  "要": { p: "yào", t: "istemek" },
  "晚上": { p: "wǎnshang", t: "akşam" },
  "朋友们": { p: "péngyoumen", t: "arkadaşlar" },
  "朋友": { p: "péngyou", t: "arkadaş" },
  "来": { p: "lái", t: "gelmek" },
  "来了": { p: "lái le", t: "geldi" },
  "宿舍": { p: "sùshè", t: "yurt (öğrenci yurdu)" },
  "给": { p: "gěi", t: "vermek, için" },
  "礼物": { p: "lǐwù", t: "hediye" },
  "今年": { p: "jīnnián", t: "bu yıl" },
  "多大": { p: "duō dà", t: "kaç yaşında" },
  "岁": { p: "suì", t: "yaş" },
  "二十岁": { p: "èrshí suì", t: "yirmi yaşında" },
  "打开": { p: "dǎkāi", t: "açmak" },
  "一张": { p: "yī zhāng", t: "bir adet (kağıt/harita için)" },
  "地图": { p: "dìtú", t: "harita" },
  "很喜欢": { p: "hěn xǐhuān", t: "çok seviyorum" },
  "喜欢": { p: "xǐhuān", t: "sevmek, hoşlanmak" },
  "一支笔": { p: "yī zhī bǐ", t: "bir kalem" },
  "一支": { p: "yī zhī", t: "bir adet (kalem için)" },
  "支": { p: "zhī", t: "kalem için sayı birimi" },
  "一个本子": { p: "yī gè běnzi", t: "bir defter" },
  "太好了": { p: "tài hǎo le", t: "çok harika / çok iyisiniz" },
  "蛋糕": { p: "dàngāo", t: "pasta" },
  "咖啡": { p: "kāfēi", t: "kahve" },
  "玩儿": { p: "wánr", t: "eğlenmek, oynamak" },
  "玩儿得很高兴": { p: "wánr de hěn gāoxìng", t: "çok eğlenmek" },
  "得": { p: "de", t: "durum/derece belirten bağlaç" },
  "呢": { p: "ne", t: "ya ...? (soru eki)" },
  "房间": { p: "fángjiān", t: "oda" },
  "不大": { p: "bù dà", t: "büyük değil" },
  "大": { p: "dà", t: "büyük" },
  "里": { p: "lǐ", t: "iç, içinde" },
  "一张床": { p: "yī zhāng chuáng", t: "bir yatak" },
  "床": { p: "chuáng", t: "yatak" },
  "一张桌子": { p: "yī zhāng zhuōzi", t: "bir masa" },
  "桌子": { p: "zhuōzi", t: "masa" },
  "一把椅子": { p: "yī bǎ yǐzi", t: "bir sandalye" },
  "把": { p: "bǎ", t: "sandalye için sayı birimi" },
  "椅子": { p: "yǐzi", t: "sandalye" },
  "一个书柜": { p: "yī gè shūguì", t: "bir kitaplık" },
  "书柜": { p: "shūguì", t: "kitaplık" },
  "一个衣柜": { p: "yī gè yīguì", t: "bir gardırop" },
  "衣柜": { p: "yīguì", t: "gardırop, dolap" },
  "墙上": { p: "qiáng shàng", t: "duvarda" },
  "墙": { p: "qiáng", t: "duvar" },
  "上": { p: "shàng", t: "üst, üzerinde" },
  "星期六": { p: "xīngqīliù", t: "Cumartesi" },
  "课": { p: "kè", t: "ders" },
  "上午": { p: "shàngwǔ", t: "öğleden önce, sabah" },
  "银行": { p: "yínháng", t: "banka" },
  "换钱": { p: "huàn qián", t: "para bozdurmak" },
  "换": { p: "huàn", t: "değiştirmek, bozdurmak" },
  "钱": { p: "qián", t: "para" },
  "学校": { p: "xuéxiào", t: "okul" },
  "东边": { p: "dōngbian", t: "doğu tarafı" },
  "旁边": { p: "pángbiān", t: "yanı, bitişiğinde" },
  "座": { p: "zuò", t: "bina için sayı birimi" },
  "楼": { p: "lóu", t: "bina, kat" },
  "就是": { p: "jiù shì", t: "ta kendisidir" },
  "走": { p: "zǒu", t: "yürümek" },
  "走进": { p: "zǒu jìn", t: "içeri girmek" },
  "进": { p: "jìn", t: "girmek" },
  "对": { p: "duì", t: "-e doğru, -e karşı" },
  "工作人员": { p: "gōngzuò rényuán", t: "çalışan personel" },
  "人员": { p: "rényuán", t: "personel, görevli" },
  "二百": { p: "èr bǎi", t: "iki yüz" },
  "美元": { p: "měiyuán", t: "Amerikan doları" },
  "人民币": { p: "rénmínbì", t: "Çin yuanı (RMB)" },
  "吗": { p: "ma", t: "mı/mi (soru eki)" },
  "身份证": { p: "shēnfènzhèng", t: "kimlik kartı" },
  "护照": { p: "hùzhào", t: "pasaport" },
  "好的": { p: "hǎo de", t: "peki, tamam" },
  "可以": { p: "kěyǐ", t: "yapabilmek (izin/olasılık)" },
  "汇率": { p: "huìlǜ", t: "döviz kuru" },
  "一千四百四十元": { p: "yī qiān sì bǎi sì shí yuán", t: "1440 yuan" },
  "一千四百四十": { p: "yī qiān sì bǎi sì shí", t: "bin dört yüz kırk" },
  "千": { p: "qiān", t: "bin" },
  "百": { p: "bǎi", t: "yüz" },
  "数": { p: "shǔ", t: "saymak" },
  "数了数": { p: "shǔ le shǔ", t: "biraz saydı" },
  "一下": { p: "yīxià", t: "bir kere, biraz (eylem için)" },
  "对了": { p: "duì le", t: "doğru, tamam" },
  "超市": { p: "chāoshì", t: "süpermarket" },
  "东西": { p: "dōngxi", t: "eşya, şeyler" },
  "里边": { p: "lǐbian", t: "içinde, iç taraf" },
  "宿舍楼": { p: "sùshè lóu", t: "yurt binası" },
  "北边": { p: "běibian", t: "kuzey tarafı" },
  "很多": { p: "hěn duō", t: "çok fazla" },
  "水果": { p: "shuǐguǒ", t: "meyve" },
  "饮料": { p: "yǐnliào", t: "içecek" },
  "面包": { p: "miànbāo", t: "ekmek" },
  "牛奶": { p: "niúnǎi", t: "süt" },
  "等等": { p: "děngděng", t: "vesaire (vs.)" },
  "苹果": { p: "píngguǒ", t: "elma" },
  "香蕉": { p: "xiāngjiāo", t: "muz" },
  "斤": { p: "jīn", t: "yarım kilo (500g)" },
  "一斤": { p: "yī jīn", t: "yarım kilo" },
  "两斤": { p: "liǎng jīn", t: "iki jin (1 kilo)" },
  "三块五": { p: "sān kuài wǔ", t: "3.5 yuan" },
  "四块钱": { p: "sì kuài qián", t: "4 yuan" },
  "七块钱": { p: "qī kuài qián", t: "7 yuan" },
  "十一块钱": { p: "shíyī kuài qián", t: "11 yuan" },
  "两块钱": { p: "liǎng kuài qián", t: "2 yuan" },
  "九块": { p: "jiǔ kuài", t: "9 yuan" },
  "一共": { p: "yīgòng", t: "toplam" },
  "算": { p: "suàn", t: "hesaplamak" },
  "算了一下": { p: "suàn le yīxià", t: "biraz hesapladı" },
  "您": { p: "nín", t: "siz (saygı)" },
  "给您钱": { p: "gěi nín qián", t: "paranız (buyrun)" },
  "找您": { p: "zhǎo nín", t: "size para üstü vermek" },
  "找": { p: "zhǎo", t: "para üstü vermek (veya aramak)" },
  "还要": { p: "hái yào", t: "ayrıca istiyorum" },
  "别的": { p: "bié de", t: "başka, diğer" },
  "一瓶水": { p: "yī píng shuǐ", t: "bir şişe su" },
  "一瓶": { p: "yī píng", t: "bir şişe" },
  "瓶": { p: "píng", t: "şişe" },
  "水": { p: "shuǐ", t: "su" },
  "这瓶水": { p: "zhè píng shuǐ", t: "bu şişe su" },
  "买完": { p: "mǎi wán", t: "alışverişi bitirmek" },
  "回": { p: "huí", t: "dönmek" },
  "真不错": { p: "zhēn bùcuò", t: "gerçekten fena değil/iyi" },
  "真": { p: "zhēn", t: "gerçekten" },
  "不错": { p: "bùcuò", t: "fena değil, iyi" },
  "换了钱": { p: "huàn le qián", t: "parayı bozdurdu" },
  "买了水果": { p: "mǎi le shuǐguǒ", t: "meyve aldı" },
  "大卫": { p: "Dàwèi", t: "David (Özel İsim)" },
  "李美爱": { p: "Lǐ Měi'ài", t: "Li Mei-ai (Özel İsim)" },
  "安妮": { p: "Ānnī", t: "Annie (Özel İsim)" },
  "林月": { p: "Lín Yuè", t: "Lin Yue (Özel İsim)" },
  "马丁": { p: "Mǎdīng", t: "Martin (Özel İsim)" },
  "李小明": { p: "Lǐ Xiǎomíng", t: "Li Xiaoming (Özel İsim)" },
  "山本": { p: "Shānběn", t: "Yamamoto (Özel İsim)" },
  "丁老师": { p: "Dīng lǎoshī", t: "Öğretmen Ding" },
  "加拿大": { p: "Jiānádà", t: "Kanada" },
  "日本人": { p: "Rìběn rén", t: "Japon" },
  "日本": { p: "Rìběn", t: "Japonya" },
  "换成": { p: "huàn chéng", t: "bozdurup ...-e dönüştürmek" },
  "成": { p: "chéng", t: "haline gelmek, dönüşmek" },
  "骑自行车": { p: "qí zìxíngchē", t: "bisiklete binmek" },
  "骑": { p: "qí", t: "binmek (bisiklete, ata vb.)" },
  "不太远": { p: "bù tài yuǎn", t: "çok uzak değil" },
  "不太": { p: "bù tài", t: "pek ... değil" },
  "远": { p: "yuǎn", t: "uzak" },
  "去不去": { p: "qù bu qù", t: "gidecek misin, gitmeyecek misin?" },
  "有没有": { p: "yǒu méi yǒu", t: "var mı, yok mu?" },
  "现在": { p: "xiànzài", t: "şimdi, şu an" },
  "只有": { p: "zhǐ yǒu", t: "sadece ... var" },
  "只": { p: "zhǐ", t: "sadece, yalnızca" },
  "电话号码": { p: "diànhuà hàomǎ", t: "telefon numarası" },
  "电话": { p: "diànhuà", t: "telefon" },
  "号码": { p: "hàomǎ", t: "numara" },
  "找你": { p: "zhǎo nǐ", t: "seni bulmak / yanına gelmek" },
  "有空儿": { p: "yǒu kòngr", t: "vakti olmak, boş zamanı olmak" },
  "空儿": { p: "kòngr", t: "boş vakit" },
  "服务员": { p: "fúwùyuán", t: "görevli, garson" },
  "二楼": { p: "èr lóu", t: "ikinci kat" },
  "二": { p: "èr", t: "iki" },
  "这边": { p: "zhèbiān", t: "bu taraf, buraya" },
  "坐": { p: "zuò", t: "oturmak" },
  "一千二百元": { p: "yī qiān èr bǎi yuán", t: "1200 yuan" },
  "喝茶": { p: "hē chá", t: "çay içmek" },
  "第一部分": { p: "dì yī bùfèn", t: "Birinci Bölüm" },
  "第二部分": { p: "dì èr bùfèn", t: "İkinci Bölüm" },
  "第三部分": { p: "dì sān bùfèn", t: "Üçüncü Bölüm" },
  "第四部分": { p: "dì sì bùfèn", t: "Dördüncü Bölüm" },
  "第五部分": { p: "dì wǔ bùfèn", t: "Beşinci Bölüm" },
  "第一": { p: "dì yī", t: "birinci" },
  "部分": { p: "bùfèn", t: "kısım, bölüm" },
  "学校很大": { p: "xuéxiào hěn dà", t: "okul çok büyük" },
  "很大": { p: "hěn dà", t: "çok büyük" },
  "住": { p: "zhù", t: "yaşamak, kalmak" },
  "在": { p: "zài", t: "-de, -da (bulunma)" },
  "7号楼": { p: "qī hào lóu", t: "7 numaralı bina" },
  "星期四": { p: "xīngqīsì", t: "Perşembe" },
  "七点一刻": { p: "qī diǎn yī kè", t: "saat yedi çeyrek" },
  "七点": { p: "qī diǎn", t: "saat yedi" },
  "一刻": { p: "yī kè", t: "çeyrek (15 dk)" },
  "起床": { p: "qǐchuáng", t: "yataktan kalkmak" },
  "同屋": { p: "tóngwū", t: "oda arkadaşı" },
  "几点": { p: "jǐ diǎn", t: "saat kaç" },
  "快": { p: "kuài", t: "hızlı, çabuk" },
  "洗脸": { p: "xǐ liǎn", t: "yüz yıkamak" },
  "刷牙": { p: "shuā yá", t: "diş fırçalamak" },
  "八点半": { p: "bā diǎn bàn", t: "sekiz buçuk" },
  "八点": { p: "bā diǎn", t: "saat sekiz" },
  "半": { p: "bàn", t: "yarım, buçuk" },
  "上课": { p: "shàngkè", t: "derse girmek, ders başlaması" },
  "一个小时": { p: "yī gè xiǎoshí", t: "bir saat" },
  "小时": { p: "xiǎoshí", t: "saat (süre)" },
  "不太忙": { p: "bù tài máng", t: "çok meşgul değil" },
  "忙": { p: "máng", t: "meşgul" },
  "食堂": { p: "shítáng", t: "yemekhane" },
  "昨天": { p: "zuótiān", t: "dün" },
  "明天": { p: "míngtiān", t: "yarın" },
  "包子": { p: "bāozi", t: "buharda pişmiş çörek" },
  "面条": { p: "miàntiáo", t: "erişte" },
  "教室": { p: "jiàoshì", t: "sınıf, derslik" },
  "教学楼": { p: "jiàoxué lóu", t: "eğitim binası" },
  "三楼": { p: "sān lóu", t: "3. kat" },
  "天气": { p: "tiānqì", t: "hava durumu" },
  "冷": { p: "lěng", t: "soğuk" },
  "热": { p: "rè", t: "sıcak" },
  "中国老师": { p: "Zhōngguó lǎoshī", t: "Çinli öğretmen" },
  "外国": { p: "wàiguó", t: "yabancı (ülke)" },
  "漂亮": { p: "piàoliang", t: "güzel" },
  "哪国人": { p: "nǎ guó rén", t: "nereli (hangi ülkeden)" },
  "名字": { p: "míngzi", t: "isim, ad" },
  "加拿大人": { p: "Jiānádà rén", t: "Kanadalı" },
  "跟我": { p: "gēn nǐ", t: "seninle" },
  "跟": { p: "gēn", t: "ile, birlikte" },
  "没问题": { p: "méi wèntí", t: "sorun yok" },
  "十二点": { p: "shí'èr diǎn", t: "saat on iki" },
  "下课": { p: "xiàkè", t: "dersin bitmesi" },
  "饿不饿": { p: "è bu è", t: "aç mısın değil misin?" },
  "饿": { p: "è", t: "aç (karnı aç)" },
  "好啊": { p: "hǎo a", t: "olur, tamam" },
  "牛肉": { p: "niúròu", t: "dana eti" },
  "鸡肉": { p: "jīròu", t: "tavuk eti" },
  "看见": { p: "kànjiàn", t: "görmek" },
  "一个人": { p: "yī gè rén", t: "tek başına, bir kişi" },
  "坐在那儿": { p: "zuò zài nàr", t: "orada oturmak" },
  "姐姐": { p: "jiějie", t: "abla" },
  "饭": { p: "fàn", t: "yemek, pilav" },
  "两点": { p: "liǎng diǎn", t: "saat iki" },
  "三百": { p: "sān bǎi", t: "üç yüz" },
  "新鲜": { p: "xīnxiān", t: "taze" },
  "卖水果的人": { p: "mài shuǐguǒ de rén", t: "meyve satan kişi" },
  "卖": { p: "mài", t: "satmak" },
  "这种": { p: "zhè zhǒng", t: "bu tür/çeşit" },
  "那种": { p: "nà zhǒng", t: "o tür/çeşit" },
  "五块": { p: "wǔ kuài", t: "beş yuan" },
  "两块五": { p: "liǎng kuài wǔ", t: "2.5 yuan" },
  "行不行": { p: "xíng bu xíng", t: "olur mu olmaz mı?" },
  "好吧": { p: "hǎo ba", t: "peki, tamam" },
  "不要了": { p: "bù yào le", t: "istemiyorum / yeterli" },
  "晚饭": { p: "wǎnfàn", t: "akşam yemeği" },
  "附近": { p: "fùjìn", t: "civar, yakınlar" },
  "饭馆": { p: "fànguǎn", t: "restoran, lokanta" },
  "后边": { p: "hòubian", t: "arka taraf" },
  "小": { p: "xiǎo", t: "küçük" },
  "好吃": { p: "hǎochī", t: "lezzetli" },
  "咱们": { p: "zánmen", t: "biz (konuşanı ve dinleyeni kapsar)" },
  "怎么": { p: "zěnme", t: "nasıl" },
  "走路去": { p: "zǒulù qù", t: "yürüyerek gitmek" },
  "走路": { p: "zǒulù", t: "yürümek" },
  "坐我的自行车": { p: "zuò wǒ de zìxíngchē", t: "benim bisikletime otur/bin" },
  "热闹": { p: "rènao", t: "canlı, hareketli, kalabalık" },
  "几位": { p: "jǐ wèi", t: "kaç kişi (saygılı)" },
  "位": { p: "wèi", t: "kişi için saygı sözcüğü" },
  "两位": { p: "liǎng wèi", t: "iki kişi (saygılı)" },
  "吃点儿什么": { p: "chī diǎnr shénme", t: "ne yemek istersiniz?" },
  "吃点儿": { p: "chī diǎnr", t: "biraz yemek" },
  "点儿": { p: "diǎnr", t: "biraz" },
  "点一个牛肉": { p: "diǎn yī gè niúròu", t: "bir dana eti sipariş etmek" },
  "点": { p: "diǎn", t: "sipariş vermek / saat" },
  "鱼": { p: "yú", t: "balık" },
  "可乐": { p: "kělè", t: "kola" },
  "三十五": { p: "sānshíwǔ", t: "otuz beş" },
  "二十八": { p: "èrshíbā", t: "yirmi sekiz" },
  "七十六": { p: "qīshíliù", t: "yetmiş altı" },
  "不客气": { p: "bù kèqì", t: "rica ederim" },
  "睡觉": { p: "shuìjiào", t: "uyumak" },
  "十点": { p: "shí diǎn", t: "saat on" },
  "辆": { p: "liàng", t: "araçlar için sayı birimi" },
  "张": { p: "zhāng", t: "düz, yassı nesneler için sayı birimi" },
  "本": { p: "běn", t: "kitap, dergi için sayı birimi" },
  "柜子": { p: "guìzi", t: "dolap" },
  "书架": { p: "shūguì", t: "kitaplık, raf" },
  "左": { p: "zuǒ", t: "sol" },
  "右": { p: "yòu", t: "sağ" },
  "毛": { p: "máo", t: "1/10 yuan (Jiao)" },
  "分": { p: "fēn", t: "1/100 yuan / dakika" },
  "万": { p: "wàn", t: "on bin" },
  "坐车": { p: "zuò chē", t: "arabaya/otobüse binmek" },
  "打 de": { p: "dǎ dī", t: "taksi çağırmak" },
  "公共汽车": { p: "gōnggòng qìchē", t: "otobüs" },
  "出租车": { p: "chūzūchē", t: "taksi" },
  "明天见": { p: "míngtiān jiàn", t: "yarın görüşürüz" },
  "见": { p: "jiàn", t: "görüşmek" },
  "借": { p: "jiè", t: "ödünç almak/vermek" },
  "出发": { p: "chūfā", t: "yola çıkmak" },
  "前边": { p: "qiánbian", t: "ön taraf" },
  "西边": { p: "xībian", t: "batı tarafı" },
  "南边": { p: "nánbian", t: "güney tarafı" },
  "上边": { p: "shàngbian", t: "üst taraf" },
};

const READING_STORIES = [
  {
    id: 1,
    title: "故事一：新同学 (Yeni Sınıf Arkadaşı)",
    text: "我叫大卫，是法国人。我是北京语言大学的留学生。我们班有22个学生，15个男生，7个女生。我们都学习汉语。\n今天，一个新同学来我们班。她叫李美爱，是韩国人。她不是中国人。她有词典、本子和笔。她也没有自行车。\n我问她：“你家有几口人？”\n她说：“我家有四口人：爸爸、妈妈、哥哥和我。我爸爸是大夫，妈妈是老师。我哥哥是学生，他学习英语。”\n我又问：“你哥哥做什么工作？”\n她说：“他不是工作，他是学生。”\n我们班 of 同学都欢迎她。丁老师也说：“你好！欢迎你！”\n李美爱很高兴。她说：“谢谢！我很高兴认识大家！”",
    questions: [
      { q: "大卫是哪国人？ (David hangi ülkedendir?)", a: "大卫是法国人。" },
      { q: "他们班有多少学生？ (Sınıflarında kaç öğrenci var?)", a: "22个学生。" },
      { q: "新同学叫什么名字？她哪国人？ (Yeni öğrencinin adı ne? Hangi ülkeden?)", a: "李美爱。韩国人。" },
      { q: "李美爱家有几口人？谁？ (Ailesinde kaç kişi var? Kimler?)", a: "四口人：爸爸、妈妈、哥哥和她。" },
      { q: "李美爱的爸爸做什么工作？ (Babası ne iş yapıyor?)", a: "大夫 (Doktor)。" }
    ]
  },
  {
    id: 2,
    title: "故事二：生日快乐 (Doğum Günün Kutlu Olsun)",
    text: "五月九号是安妮的生日。那天是星期二。\n早上，安妮问林月：“今天几月几号星期几？”\n林月说：“今天五月九号星期二. 是你的生日！祝你生日快乐！”\n安妮很高兴：“谢谢！”\n中午，安妮和林月一起去吃饭。林月问：“你吃米饭还是饺子？”\n安妮说：“我吃饺子。你呢？”\n林月说：“我也吃饺子。你喝不喝啤酒？”\n安妮说：“我不喝啤酒。我喝茶。”\n下午，她们去书店。安妮想买一本书送给她的妹妹。她问售货员：“请问，这本书多少钱？”\n售货员说：“这本书二十五块。”\n安妮说：“太贵了！便宜一点儿吧。”\n售货员说：“二十块，怎么样？”\n安妮说：“行！我要了。”\n晚上，安妮的朋友们都来她的宿舍。大卫、山本、马丁和李小明都来了。他们给安妮送礼物。\n李小明问：“安妮，你今年多大？”\n安妮说：“我今年二十岁。”\n大卫说：“这是我送你的礼物。”\n安妮打开礼物，是一张中国地图。安妮说：“谢谢！我很喜欢！”\n山本送她一支笔，马丁送她一个本子。\n安妮说：“谢谢大家！你们太好了！”\n大家一起吃蛋糕，喝咖啡，玩儿得很高兴。",
    questions: [
      { q: "安妮的生日是几月几号星期几？ (Doğum günü hangi gün?)", a: "五月九号星期二。" },
      { q: "安妮和林月中午吃什么？喝什么？ (Öğlen ne yiyip içiyorlar?)", a: "吃饺子，喝茶。" },
      { q: "安妮给谁买书？ (Kime kitap alıyor?)", a: "她的妹妹 (Kız kardeşine)。" },
      { q: "那本书多少钱？最后多少钱买了？ (Kitap ne kadardı? Sonuçta kaça aldı?)", a: "二十五块。二十块买了。" },
      { q: "谁送安妮一张地图？ (Kim harita hediye etti?)", a: "大卫 (David)。" }
    ]
  },
  {
    id: 3,
    title: "故事三：在银行和超市 (Bankada ve Süpermarkette)",
    text: "马丁的房间不大。房间里有一张床、一张桌子、一把椅子、一个书柜和一个衣柜。墙上有一张中国地图。桌子上有一本书、一个本子和一支笔。\n今天是星期六，马丁没有课. 他上午去银行换钱。\n银行在学校的东边，书店的旁边. 那座白色的楼就是银行。\n马丁走进银行，对工作人员说：“你好，我想换二百美元的人民币。”\n工作人员问：“请问，你有身份证吗？”\n马丁说：“有. 这是我的护照。”\n工作人员说：“好的. 今天汇率是1美元换7.2元人民币. 二百美元可以换一千四百四十元人民币。”\n工作人员给他钱：“这是一千四百四十元，请数一下。”\n马丁数了数：“对了，谢谢！”\n下午，马丁去超市买东西. 超市在学校里边，宿舍楼的北边。\n超市里东西很多. 有水果、饮料、面包、牛奶等等。\n马丁想买苹果和香蕉. 他问售货员：“请问，苹果多少钱一斤？”\n售货员说：“苹果三块五一斤. 香蕉四块钱一斤。”\n马丁说：“我要两斤苹果、一斤香蕉. 一共多少钱？”\n售货员算了一下：“两斤苹果是七块钱，一斤香蕉是四块钱，一共十一块钱。”\n马丁说：“给您钱. 这是二十块。”\n售货员说：“找您九块. 谢谢！还要别的吗？”\n马丁说：“还要一瓶水. 这瓶水多少钱？”\n售货员说：“两块钱。”\n马丁说：“好，我要了。”\n马丁买完东西，回宿舍. 他想：“今天真不错，换了钱，也买了水果。”",
    questions: [
      { q: "马丁的房间有什么？ (Odada neler var?)", a: "床、桌子、椅子、书柜、衣柜、地图、书、本子、笔。" },
      { q: "银行在哪儿？ (Banka nerede?)", a: "在学校的东边，书店的旁边。" },
      { q: "马丁去银行做什么？ (Bankaya ne yapmaya gidiyor?)", a: "换钱 (Para bozdurmaya)。" },
      { q: "马丁换多少钱？换多少人民币？ (Kaç dolar bozdurup kaç yuan alıyor?)", a: "二百美元。一千四百四十元人民币。" },
      { q: "马丁买了什么？一共多少钱？ (Ne aldı? Toplam ne kadar tuttu?)", a: "两斤苹果，一斤香蕉，一瓶水. 一共十三块钱 (11 + 2)。" }
    ]
  },
  {
    id: 4,
    title: "故事十一：去银行换钱 (Bankaya Para Bozdurmaya Gitmek)",
    text: "今天是星期六，我没有课. 上午，我去银行换钱. 我有二百美元，想换成人民币。\n我骑自行车去银行. 银行在学校的东边，不太远. 我问我的朋友马丁：“马丁，你去不去银行？”\n马丁说：“我不去银行. 我要去超市买东西. 你有没有人民币？”\n我说：“我没有人民币，现在只有美元. 我去银行换钱。”\n马丁说：“你的电话号码是多少？下午我去你宿舍找你，我们一起玩儿，怎么样？”\n我说：“好的！我的电话号码是82306154. 有空儿来我宿舍玩儿！”\n我骑自行车去银行. 银行里人很多. 我问服务员：“请问，换钱在哪儿？”\n服务员说：“在二楼. 请这边坐。”\n我换了一千二百元人民币. 我很高兴！下午，马丁来我宿舍找我. 我们一起喝茶，吃饺子. 我们都很高兴！",
    questions: [
      { q: "今天星期几？大卫有没有课？ (Bugün günlerden ne? David'in dersi var mı?)", a: "今天星期六，大卫没有课。" },
      { q: "大卫上午去做什么？ (David sabah ne yapmaya gidiyor?)", a: "他去银行换钱。" },
      { q: "大卫有多少美元？他想换成什么钱？ (David'in ne kadar doları var? Hangi paraya çevirmek istiyor?)", a: "他有二百美元。他想换成人民币。" },
      { q: "银行在哪儿？ (Banka nerede?)", a: "银行在学校的东边。" },
      { q: "马丁去不去银行？他去哪儿？ (Martin bankaya gidiyor mu? O nereye gidiyor?)", a: "马丁不去银行. O nereye gidiyor?" },
      { q: "大卫的电话号码是多少？ (David'in telefon numarası ne?)", a: "82306154。" },
      { q: "银行里人多么？ (Bankada insanlar çok mu?)", a: "银行里人很多。" },
      { q: "大卫换了多少钱？ (David ne kadar para bozdurdu?)", a: "他换了一千二百元人民币。" },
      { q: "下午马丁来宿舍找大卫做什么？ (Öğleden sonra Martin yurda David'i bulmaya gelince ne yapıyorlar?)", a: "他们一起喝茶，吃饺子。" }
    ]
  },
  {
    id: 5,
    title: "故事十二：我在北京的一天 (Pekin'de Bir Günüm)",
    text: "第一部分：早上 (Sabah)\n我叫大卫，是法国人. 我是北京语言大学的留学生. 我们学校很大，有很多楼. 我住在学生宿舍，在7号楼301房间. 我的电话号码是82306154。\n今天是星期四，早上七点一刻，我起床了. 我问我同屋：“现在几点了？”\n他说：“现在七点一刻. 你快起床吧！”\n我说：“好的，谢谢！”\n我很快起床，洗脸、刷牙. 我早上八点半上课，还有一个小时. 我不太忙。\n我问同屋：“你早上吃什么？我们去食堂吃饭，好吗？”\n同屋说：“我不去食堂. 我昨天买了面包和牛奶. 你呢？”\n我说：“我去食堂吃. 食堂有米饭、包子、饺子和面条. 我喜欢吃饺子。”\n早上八点，我骑自行车去教室. 我们教室在教学楼三楼. 今天天气很好，不冷也不热。\n\n第二部分：在教室 (Sınıfta)\n我们班有22个学生，15个男生，7个女生. 我们都学习汉语. 我们班有中国老师，也有外国学生. 我的中国老师是丁老师，她很好，也很漂亮。\n今天一个新同学来我们班. 她叫李美爱，是韩国人. 她不是中国人. 她有词典、本子和笔. 我问她：“你好！你是哪国人？”\n她说：“我是韩国人. 你叫什么名字？”\n我说：“我叫大卫，是法国人. 欢迎你来我们班！”\n她很高兴，说：“谢谢！我很高兴认识你。”\n丁老师问她：“你家有几口人？”\n李美爱说：“我家有四口人：爸爸、妈妈、哥哥和我。”\n丁老师又问：“你爸爸做什么工作？”\n她说：“我爸爸是大夫，妈妈是老师. 我哥哥是学生，他学习英语。”\n这时候，马丁也来了. 马丁是我的朋友，他是加拿大人. 他问我：“大卫，你有没有人民币？我想跟你换钱。”\n我说：“我没有人民币，我只有美元. 下午我去银行换钱，你可以跟我一起去。”\n马丁说：“好的！下午几点去？”\n我说：“我们下午两点去银行，怎么样？”\n马丁说：“没问题！”\n\n第三部分：中午 (Öğle Vakti)\n中午十二点，我们下课了. 我问李美爱：“你饿不饿？我们去食堂吃饭吧！”\n李美爱说：“好啊！食堂有什么？”\n我说：“食堂有米饭、饺子、包子、面条，还有牛肉和鸡肉. 你吃米饭还是饺子？”\n李美爱说：“我吃饺子. 你呢？”\n我说：“我也吃饺子. 你喝不喝啤酒？”\n李美爱说：“不喝，我喝茶。”\n在食堂，我们看见山本. 山本是日本人，他也是我们班的同学. 他一个人坐在那儿吃饭。\n我们问他：“山本，你吃什么呢？”\n山本说：“我吃面条. 你们坐这儿吧！”\n我们三个人一起吃饭，很高兴. 李美爱问山本：“你家有几口人？”\n山本说：“我家有四口人：爸爸、妈妈、姐姐和我。”\n李美爱又问：“你姐姐做什么工作？”\n山本说：“我姐姐是大夫. 她工作很忙。”\n吃完饭，我问服务员：“请问，一共多少钱？”\n服务员说：“饺子十块，茶两块，一共十二块。”\n我给她二十块钱，她找我八块钱。\n\n第四部分：下午 (Öğleden Sonra)\n下午两点，我和马丁去银行换钱. 银行在学校的东边，不太远. 我们骑自行车去。\n我问马丁：“你换多少钱？”\n马丁说：“我换三百美元的人民币. 你呢？”\n我说：“我换二百美元。”\n银行里人很多. 我问服务员：“请问，换钱在哪儿？”\n服务员说：“在二楼. 请这边坐。”\n我们换了钱，我很高兴. 我有了一千二百元人民币。\n我问马丁：“现在我们去哪儿？”\n马丁说：“我想去超市买东西. 你呢？”\n我说：“好的，我也去超市. 我想买水果。”\n在超市，水果很新鲜. 我问卖水果的人：“苹果多少钱一斤？”\n他说：“这种苹果三块一斤，那种五块一斤。”\n我说：“这种太贵了！便宜一点儿吧，两块五一斤，怎么样？”\n他说：“好吧，两块五一斤. 你要几斤？”\n我说：“我要两斤。”\n我又问：“香蕉多少钱一斤？”\n他说：“香蕉四块一斤。”\n我说：“太贵了！三块五一斤，行不行？”\n他说：“行吧，三块五一斤。”\n我买了苹果和香蕉，一共十二块钱. 我给他十五块，他找我三块。\n马丁买了面包、牛奶、咖啡和啤酒. 他问我：“大卫，你还要别的吗？”\n我说：“不要了. 我们回学校吧。”\n\n第五部分：晚上 (Akşam)\n晚上六点，李美爱来我宿舍找我. 她问我：“大卫，学校附近有没有饭馆？我想去吃晚饭。”\n我说：“有. 学校后边有一个小饭馆，很好吃. 咱们怎么去？”\n李美爱说：“我没有自行车，我走路去. 你呢？”\n我说：“我骑自行车去. 你坐我的自行车吧！”\n李美爱说：“好的，谢谢！”\n我们一起去饭馆. 饭馆里人很多，很热闹. 服务员问我们：“欢迎！请问几位？”\n我说：“两位。”\n服务员说：“请这边坐. 两位吃点儿什么？”\n李美爱问我：“这儿有什么好吃的？”\n我说：“有米饭、饺子、面条，还有牛肉、鸡肉和鱼. 你吃米饭还是面条？”\n李美爱说：“我吃米饭. 你吃什么？”\n我说：“我也吃米饭. 我们点一个牛肉，一个鱼，怎么样？”\n李美爱说：“好啊！你喝不喝啤酒？”\n我说：“我喝啤酒. 你呢？”\n李美爱说：“我不喝啤酒，我喝可乐。”\n服务员问：“还要别的吗？”\n我说：“不要了，谢谢！一共多少钱？”\n服务员说：“牛肉三十五，鱼二十八，啤酒八块，可乐五块，一共七十六块。”\n吃完饭，我们很高兴. 李美爱说：“今天我很高兴！谢谢你，大卫！”\n我说：“不客气！我们是朋友！”\n我们骑自行车回学校. 晚上十点，我睡觉了。",
    questions: [
      { q: "大卫是哪儿人？他现在在哪儿？", a: "大卫是法国人. 他现在在北京语言大学留学。" },
      { q: "大卫早上几点起床？他早上几点上课？", a: "他早上七点一刻起床. 他早上八点半上课。" },
      { q: "大卫早上在食堂吃什么？", a: "他吃饺子. 他不吃包子，也不吃面条。" },
      { q: "李美爱是哪国人？她家有几口人？", a: "李美爱是韩国人. 她家有四口人：爸爸、妈妈、哥哥和她。" },
      { q: "李美爱的爸爸做什么工作？她妈妈呢？", a: "她爸爸是大夫. 她妈妈是老师。" },
      { q: "马丁是哪国人？下午他和大卫去做什么？", a: "马丁是加拿大人. 下vu他和大卫去银行换钱。" },
      { q: "大卫换了多少钱？他有多少人民币？", a: "他换了二百美元的人民币. 他有一千二百元人民币。" },
      { q: "在超市，苹果多少钱一斤？大卫买了几斤？", a: "苹果两块五一斤. 他买了两斤。" },
      { q: "晚上大卫和李美爱去哪儿吃饭？他们怎么去？", a: "他们去学校后边的小饭馆吃饭. 大卫骑自行车，李美爱坐他的自行车。" },
      { q: "他们晚上吃了什么？一共多少钱？", a: "它们吃了米饭、牛肉和鱼. 一共七十六块。" },
      { q: "大卫晚上几点睡觉？", a: "他晚上十点睡觉。" }
    ],
    vocabUnits: [
      { unit: "1. Ünite (Tanışma)", words: "我、你、他、她、我们、你们、他们、是、叫、也、不、法国、中国、日本、韩国、加拿大、老师、学生、朋友" },
      { unit: "2. Ünite (Eşyalar)", words: "书、词典、本子、笔、地图、有、没有、的、个、本、张、支、辆" },
      { unit: "3. Ünite (Aile)", words: "家、几口人、爸爸、妈妈、哥哥、姐姐、工作、大夫" },
      { unit: "4. Ünite (Sınıf ve Sayılar)", words: "班、多少、学习、汉语、英语、名字、哪国人、电话号码" },
      { unit: "5. Ünite (Tarih)", words: "今天、昨天、明天、月、号、星期、生日、快乐、礼物" },
      { unit: "6. Ünite (Saat)", words: "早上、上午、中午、下午、晚上、点、刻、半、分、起床、上课、下课、睡觉" },
      { unit: "7. Ünite (Yer ve Yön)", words: "银行、学校、宿舍、超市、饭馆、东边、西边、南边、北边、前边、后边、旁边、在、哪儿" },
      { unit: "8. Ünite (Oda ve Eşyalar)", words: "房间、桌子、椅子、床、柜子、书架、墙上、里边、上边、左、右" },
      { unit: "9. Ünite (Yemek)", words: "吃、喝、米饭、饺子、包子、面条、面包、啤酒、茶、咖啡、可乐、还是、吧" },
      { unit: "10. Ünite (Alışveriş)", words: "钱、块、毛、分、斤、苹果、香蕉、贵、便宜、太……了、多少、怎么、怎么样" },
      { unit: "11. Ünite (Bankacılık)", words: "换钱、人民币、美元、百、千、万、有空儿、来、玩儿、住、电话、号码" },
      { unit: "12. Ünite (Ulaşım)", words: "骑自行车、走路、坐车、打 de、公共汽车、出租车、怎么、一起、明天见、借、辆、出发" }
    ]
  }
];
